### ISSUE TITLE
updates updates

### ISSUE THREAD

**Issue by level20peon** [freeshrugsxd/wow-addon-updater#1]
Hello,

I liked your script so I spent a little time to base my own on it. I'll attach it, so maybe you can use some of the functionality. I stripped the multiprocessing and color fonts, because I didn't want to get into that.
However, I added:
- configuration moved to external .ini file
- the ini file also contains the functionality your .json offered before, so its readability improved
- I did some general cleanup (variables, logic, etc.)
- I added a backup option (the whole addons & wtf folder is backed up, optional setting in the .ini file)
- classic / retail are also .ini options now

Maybe you'll find it useful. I would be interested in how you would adapt it (if you put in multiprocessing again, for example). Note that there still is *some* cleanup that could be done I guess, but I think I'm done for the day :)

Regards
[update_wow_addons.zip](https://github.com/freeshrugsxd/wow-addon-updater/files/3659275/update_wow_addons.zip)

**Comment by freeshrugsxd** [comment]
Hey man,

glad you liked it! I had a look at your code and I really like the idea of storing config, addon list and update timestamps in a single file. Might do something similar for my script!

The optional addon backups are also very nice! Would be overkill for me to backup on every execution as I often check for updates multiple times a day. I don't really see the point in backing up the WTF folder on addon updates though - is that just to be safe or am I missing something?

I'm not really comfortable with OOP in Python. I have an easier time thinking about data getting passed from function to function than having everything in a class. Although I guess it will make more sense once this project reaches a certain size. I will have to think about this. But this also means that I wouldn't really know where multiprocessing would fit in here - but I guess it can't be that hard and it's definitely worth it! 

Another thing we should probably consider is having separate update lists for classic and retail. Because when switchen versions, there is not way to tell if the saved update timestamp is for retail or classic. 
Maybe two sections in the .ini file?
```
[classic]
addon1
addon2
...
```
```
[retail]
addon1
addon3
...
```
I only play one version so it never occurred to me that this could be a problem. But organizing it like this would enable the user to keep two separate sets of addons up-to-date respectively, which is pretty neat.

You are the first person to ever reach out to me on here for anything and I'm really excited and thankful for your input!

Cheers

**Comment by level20peon** [comment]
Hey,

I agree that backing up all addons every single time would be overkill, so I will probably change this behaviour to only backup updated addons. For that I will need to read the content of the addon's .zip archive in order to determine the folders it contains. Maybe that would be a more elegant solution!?

The WTF folder contains the config data for all addons (and non-addon options) so I think it's not a bad idea to back this up before potentially screwing up that config due to a bad / incompatible update. It's not *that* big either (~20MB zipped in my case) so with an average storage capacity, it's negligible. But maybe another strategy would be to back it up once a week, if you run the script multiple times per day? I'll look into that.

The OOP part isn't that complicated, really. As you can see I also pass around data from function to function. I'm just doing it all inside an object. To be honest, I only used this structure, because your original script wouldn't run without throwing errors. I think that's maybe due to different environments in use. So I took the structure of another project and simply inserted your script in there, with slight tweaks and went on from there. I don't think that multiprocessing would be an issue if we use only one object anyways. I never used multiprocessing before and couldn't get it to work in a reasonable time, but that's only because I overhauled the complete variable structure and then didn't know how to get back :) (again, reasonable time, there's no point in putting days into this if it just works). Also, I don't know if it's beneficial to use multiprocessing when checking ~50 addons for updates and then maybe updating ~5 in the end, but I don't know your thought process on that, so.

Separate lists for classic and retail are a great idea. I didn't think about this because I also only use one version of the game. But for someone who uses both, simply switching wouldn't really be possible without separate .ini files. So I'll also look into that.

Yeah, why not combine resources? I lost too much time on trying to prevent using the twitch client (full on bloatware for just updating a few files in my opinion) by testing minion for wowinterface.com and so I ended up here after contemplating about writing something from scratch :)

**Comment by freeshrugsxd** [comment]
Hey, I was gonna ask you what errors you ran into when using my script but then I spend some time in a Windows 10 virtualbox and I think I hit the same wall you did. I was not aware that multiprocessing works so fundamentally different on Windows and Unix. I thought I found an ez fix by just calling multiprocessing.freeze_support() but for this to work I'll have to rework the flow of at least part of the program. I'm pretty invested now because I really want this to work on Windows and I also really want it to be fast.

> I don't know if it's beneficial to use multiprocessing when checking ~50 addons for updates and then maybe updating ~5 in the end

It is really not that important how many files are updated in the end. The bottleneck are the get requests. It takes about a second after every request until you have the response object to work with. This means that only checking for updates of 50 addons almost takes a minute when you do it asynchronously. The same is true when there are updates to be downloaded. As you can see in the [demo](https://i.imgur.com/F6YleIb.gif), checking for 41 updates usually takes about 2.5 to 4 seconds on my machine (8 cores, meaning 16 workers, so YMMV). When I tested your script the other day it took more than two minutes to update 40-something addons. I had similar execution times before I added multiprocessing and I couldn't stand how long it took for something that simple. Especially since 80-90% of it's duration, the program is just waiting for a response.

> But for someone who uses both, simply switching wouldn't really be possible without separate .ini files. So I'll also look into that.

I was actually thinking of a single ini file with just two separate sections. I like the idea of having everything stored in a single file.

**Comment by level20peon** [comment]
> But for someone who uses both, simply switching wouldn't really be possible without separate .ini files. So I'll also look into that.
>I was actually thinking of a single ini file with just two separate sections. I like the idea of having everything stored in a single file.

That's what I meant ;)

**Comment by freeshrugsxd** [comment]
The latest commit https://github.com/freeshrugsxd/wow-addon-updater/commit/ff4e182e9fcece4528a24b4ce6e4fa9938ddb9aa got multiprocessing working on my Win10 VM. Would you care to take a look and confirm that it works? I need sleep now.

**Comment by level20peon** [comment]
Ok I had a look and it seems to work.
I also made a few changes - this time I changed your code instead of creating my own, so you can run a diff on the attachment. I'll explain what I did (and would do) here:

0) You are too fast, I was working on my updates while you pushed the latest commit ;)
1) I like the way you allow for both versions to be updated simultaeously!
2) Why do you initialize _cfscrape.create_scraper()_ for every instance, instead of initializing it once, globally (like I did in my first post)? Is this required for multithreading?
3) Why do you switch based on Windows vs Linux for printing output? Could you elaborate on that?
4) Your windows / linux detection seemed less elegant than I already used it in other projects, so I updated the proper sections in the script.
5) Why do you set the cache dir to be in your home dir? I think I would rather place it into the same dir as the script (which in turn, _could_ be in your home dir of course). The _expanduser('~')_ will expand to "C:\Users\foo" on Windows, which really isn't the place one should store anything, without using a subdirectory further down ("AppData\Roaming", etc.). But even then, it's not a place I would store any data at all, rather than chosing my own path (the script path, for example ;) ).
6) I reworked the backup function so it will only backup the addon folders which are overwritten in an update. I also expanded the config file options for backups (backup nothing / backup replaced addons / backup replaced addons + WTF folder).
7) I added the possibility to add addons from github. I don't want to open the can of worms to start supporting other sites like wowinterface.com, but some addons are not present on any of the platforms rather than just being small scripts on a public repository.
8) I had a datatype conversion error on the check when the last addon update waas compared to the current timestamp on curseforge. It seems that the last addon update is read as _str_ if there already is a timestamp present in the config. When comparing that to a numerical data type, it throws an error. So I converted the last addon update to a _float_ for comparison.
9) I added _abspath_ to all instances of _pjoin_ in order to tackle a symlink issue on Windows, which might occur after using _mklink_.
10) Note: it takes quite a while for the child workers to spawn (like 1 seconds per worker, and then a 1 second pause after spawning 3 workers). I don't know if that's normal. That's quite a while since they are spawned (and then disposed of) twice in the script.
11) Note: There is a strange display bug with _colorama_ I guess: the download rate most of the time shows "it/s" and sometimes "s/it" - both of which seem wrong. I think that should be "Mbit/s", or am I wrong?
12) Note: So many hours went into this already, but it's definitely done now for sure (TM) :)

for (6) and (7) please have a look at the config file example I attached. For (7) I also added a switch for the config file which will ignore all addons that are listed on other platforms. I find it useful to have them listed in the config anyways for trying to keep track of addons on those other sites (if any).


Regards
[191003_updates.zip](https://github.com/freeshrugsxd/wow-addon-updater/files/3683594/191003_updates.zip)

**Comment by freeshrugsxd** [comment]
Hey, thank you very much for putting up with this!

>0. You are too fast, I was working on my updates while you pushed the latest commit ;)

:D

>1. I like the way you allow for both versions to be updated simultaeously!

Thanks! It felt clumsy to always open the config file to switch the client. The implementation is not really flexible but since there are only two clients it's good enough for now I guess :man_shrugging: 

>2. Why do you initialize cfscrape.create_scraper() for every instance, instead of initializing it once, globally (like I did in my first post)? Is this required for multithreading?

I actually never thought about reusing one instance of the scraper. It is not really required I think. It's just how I thought you'd use this class. I did a quick test with a single instance and the results look promising! The changes are already committed and I will push it later today!

>3. Why do you switch based on Windows vs Linux for printing output? Could you elaborate on that?

Why yeah, that's a problem I couldn't solve when I was troubleshooting multiprocessing for Windows. When Pool starts a new process, this process has its own private set of copies for all variables. Because I want that little animation to play, I need an index to pass on to the print function. If I just assign 0 to a variable, every process just increments its own copy of that index from 0 to 1.  Changes made inside the processes are not propagated to the main process. That's why I used shared memory objects, such as Manager or Value, to have objects (dictionaries, int values) that all processes had access to. This worked fine on Linux but it's apparently not that simple on Windows, because of the way the processes are created. I don't really understand all the details but what I got was, while I can just implicitly reference shared objects in any function/method under Linux, for the same function/method to work on Windows I have to explicitly pass the shared objects on through inheritance. [And I only figured out how to do that an hour ago](https://stackoverflow.com/a/53621343). Because I didn't know how to deal with shared objects under Windows but still wanted my animation to play on Linux, I just put in the Windows-condition until I would find a fix for this. I got it working now (although there are glitches), which means the windows-flag will probably either go away or only be used to decide for a default cache directory or something like that.

>4. Your windows / linux detection seemed less elegant than I already used it in other projects, so I updated the proper sections in the script.

k

>5. Why do you set the cache dir to be in your home dir? 

That's where all my stuff is! Plus, there already is a .cache folder that other applications are using, so it is just convenient for me. I was thinking about putting it into %APPDATA% or something but I didn't really spend much time figuring out a good solution. I would go with whatever people prefer! And in case the default doesn't suit everybody, this could also be an optional, uhm, _option_, inside the config file.


>6. I reworked the backup function so it will only backup the addon folders which are overwritten in an update.

I like the options you put in place! I will think about how to incorporate this. With backups on every update, this could potentially pile up pretty quick. Especially since there are quite large database addons that get updated very regularly. For example:
* raiderio:                  30/72MB zipped/unzipped, updated twice a day
* undermine journal:  36/82MB zipped/unzipped, updated twice a week 

Over the last ten years I have backed up my AddOns and WTF folders, like, twice. But weird things happen when you automate stuff so I guess it's fair to play it safe.

>7. I added the possibility to add addons from github. 

Ooooooh that one is pretty cool! I will take a look at it, once I have some time!

>8. I had a datatype conversion error

Yeah I fixed that with the commit (c7da647069df786678674bc8f3d3db1a01361db0) you mentioned in (0) :D

>9. I added abspath to all instances of pjoin in order to tackle a symlink issue on Windows, which might occur after using mklink.

Okay, I will take a look how it affects things but I think this should be fine. What's the issue, exactly?

>10. Note: it takes quite a while for the child workers to spawn (like 1 seconds per worker, and then a 1 second pause after spawning 3 workers). I don't know if that's normal.

Doesn't sound normal to me. How many workers did you use? Did you use the 2 you defined in your script or did you also try `cpu_count` or `cpu_count*2`? I mean, I have some variation in my execution times, too, ~~and it seems to be somewhat slower on Windows in general~~. (I just realized my Win10 VM has only 4 processors. That's why it's slower.... moving on) 

The number of workers is the number of parallel operations. When you have only 2 workers, then of course you will see some downtime when one of them, or both, take a bit longer for their request to get a response. As I mentioned the other day, on my system it takes about a second for a request to receive a response object. The advantage of doing this in parallel is that, when you have 12 worker starting their request at the same time, you have 12 responses ready after ~1s. At least that's how I picture it.  I also assume that most of the variation in the processing duration comes from curse being busy or the internet connection being wonky for a moment.

> 11. There is a strange display bug with colorama

Colorama does nothing except for coloring terminal output. The progress bar comes from the tqdm module and the _**it**_ in it/s means iteration. In our case, it's the number of processed addons per second or the average time it took for one addon to be processed. Because the progress bar is wrapped around the Pool for the `update_addon` function, it progresses when one of the slave processes is done. You can [customize tqdm](https://github.com/tqdm/tqdm#documentation) quite a bit, but I haven't gotten around to do it yet.

>12. So many hours went into this already, but it's definitely done now for sure (TM) :)

I feel you man :D Thank you for the feedback! I am a long way from done :smiling_imp:

**Comment by level20peon** [comment]
6) Maybe put in an additional condition for backing up folders like: Only back them up, if a target folder is overwritten (like now) *plus* only back them up, if the last backup file is >= 1 week old?

9) The issue is that python sometimes won't accept cross drive symlinks in Windows. I had this problem when trying to tell selenium to use files (images) from a symlinked drive other than the drive I was running the script from. So I always just to the _abspath_ now, just to be safe on the cross-platform side.

10) I think the problem is PyCharm. When I run the script from the command line, the workers are spawned immediately. So that's really not something worth investing more time for investigating for now.

11) ok, tqdm then. You got an idea why it sometimes displays "s/it" instead of "it/s"? That doesn't sound to be something that occurs because it's not optimized, right?

**Comment by freeshrugsxd** [comment]
I always thought it tqdm would just sometimes switch between the both ratios. Displaying how many iterations were done per second and how long an average iteration took. But I really don't know. I changed the format though to only display current/total and the name of the addon that got updated with the last iteration.

**Comment by Magissia** [comment]
Hello, cache should be in %localappdata%\wow-addon-updater, placing it anywhere in %userprofile% root is a bad idea.

You do not want to use %appdata% for this one, there's no good reason one would wish to synchronise this script's cache back to a domain controller.
